# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ReactCPI' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for ReactCPI
  pod 'AppCenterReactNativeShared', '~> 1.3.0'
  pod 'AppCenter/Push', '~> 1.4.0'

  

  platform :ios, '9.0'
  target 'ReactCPITests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'ReactCPI-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for ReactCPI-tvOS

  target 'ReactCPI-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
